/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "All of your cursor(s) combined generates": "您的所有 游标 组合生成",
    "Blue Coins": "蓝色硬币",
    "bluecoins.": "蓝色硬币。",
    "Close": "关闭",
    "Cursor": "游标",
    "cursor(s).": "游标.",
    "Each cursor generates": "每个游标产生",
    "more cursor(s": "更多游标",
    "Next upgrade in": "下一个升级在",
    "Wipe Save": "擦除存档",
    "Prestige": "声望",
    "Settings": "设置",
    "All of your power clicker(s) combined generates": "您所有的能量点击器组合生成",
    "Autoclickers and clicking are twice as efficient": "自动点击器和点击的效率是前者的两倍",
    "Clicking efficiency is quadrupled": "点击效率翻两番",
    "Each power clicker generates": "每个能量点击器都会生成",
    "Power Clicker": "能量点击器",
    "power clicker(s).": "能量点击器。",
    "All of your commando(s) combined generates": "你所有的突击队员组合生成",
    "All of your private(s) combined generates": "您所有的列兵组合生成",
    "Bazooka": "火箭筒",
    "Butcher": "屠夫",
    "Cadet": "学员",
    "Clone Amplifier": "克隆放大器",
    "Commando": "突击队",
    "commando(s).": "突击队。",
    "Defender": "防御者",
    "Each commando generates": "每个突击队生成",
    "Each private generates": "每个列兵生成",
    "Engineer": "工程师",
    "Grenadier": "掷弹兵",
    "Gunner": "枪手",
    "Infantry": "步兵",
    "Marksman": "神射手",
    "more commando(s": "更多突击队",
    "Medic": "医生",
    "more private(s": "更多列兵",
    "Private": "列兵",
    "private(s).": "列兵。",
    "Pyro": "火焰兵",
    "Rookie": "菜鸟",
    "Sniper": "狙击兵",
    "Sapper": "工兵",
    "Striker": "前锋",
    "Privates are twice as efficient": "列兵的效率是两倍",
    "more cadet(s": "更多学员",
    "Each cadet generates": "每个学员生成",
    "Commandos are twice as efficient": "突击队的效率是原来的两倍",
    "Cadets are twice as efficient": "学员的效率是两倍",
    "cadet(s).": "学员。",
    "All of your cadet(s) combined generates": "你所有的学员组合生成",
    "more striker(s": "更多前锋",
    "pyro(s).": "火焰兵。",
    "Pyros are twice as efficient": "火焰兵的效率是两倍",
    "Rookies are twice as efficient": "菜鸟的效率是原来的两倍",
    "sapper(s).": "工兵。",
    "Sappers are three times as efficient": "工兵的效率是原来的三倍",
    "striker(s).": "前锋。",
    "Strikers are three times as efficient": "前锋的效率是其三倍",
    "UPCOMING": "即将到来",
    "All clones bluecoin producing efficiency is doubled": "所有克隆蓝币生产效率翻倍",
    "All of your bazooka(s) combined generates": "你所有的火箭筒组合生成",
    "All of your butcher(s) combined generates": "你所有的屠夫加起来生成",
    "All of your clone amplifier(s) combined generates": "您所有的克隆放大器组合起来会生成",
    "All of your defender(s) combined generates": "你所有的防守者加起来生成",
    "All of your engineer(s) combined generates": "您的所有工程师联合生成",
    "All of your grenadier(s) combined generates": "你所有的掷弹兵联合生成",
    "All of your gunner(s) combined generates": "你所有的炮手联合生成",
    "All of your infantry(s) combined generates": "你所有的步兵联合生成",
    "All of your marksman(s) combined generates": "你所有的神射手组合生成",
    "All of your medic(s) combined generates": "你所有的医生加起来生成",
    "All of your pyro(s) combined generates": "你所有的火焰兵组合生成",
    "All of your rookie(s) combined generates": "你所有的新秀加起来生成",
    "All of your sapper(s) combined generates": "你所有的工兵结合生成",
    "All of your sniper(s) combined generates": "你所有的狙击手组合生成",
    "All of your striker(s) combined generates": "你所有的前锋加起来生成",
    "bazooka(s).": "火箭筒。",
    "Bazookas are three times as efficient": "火箭筒的效率是其三倍",
    "clone amplifier(s).": "克隆放大器。",
    "Butchers are twice as efficient": "屠夫的效率是原来的两倍",
    "defender(s).": "防御者。",
    "Defenders are twice as efficient": "防守者的效率是两倍",
    "Each bazooka generates": "每个火箭筒生成",
    "Each butcher generates": "每个屠夫生成",
    "Each clone amplifier generates": "每个克隆放大器生成",
    "Each defender generates": "每个防御者生成",
    "Each engineer generates": "每个工程师生成",
    "Each grenadier generates": "每个掷弹兵生成",
    "Each gunner generates": "每个炮手生成",
    "Each infantry generates": "每个步兵生成",
    "Each marksman generates": "每个射手生成",
    "Each medic generates": "每个医生生成",
    "Each pyro generates": "每个 火焰兵 生成",
    "Each rookie generates": "每个新秀生成",
    "Each sapper generates": "每个工兵生成",
    "Each sniper generates": "每个狙击手生成",
    "Each striker generates": "每个前锋产生",
    "Engineers are three times as efficient": "工程师的效率是原来的三倍",
    "engineer(s).": "工程师。",
    "grenadier(s).": "掷弹兵。",
    "Grenadiers are three times as efficient": "掷弹兵的效率是其三倍",
    "medic(s).": "医生。",
    "Medics are three times as efficient": "医生的效率是原来的三倍",
    "Marksmen are twice as efficient": "射手的效率是两倍",
    "Infantrymen are twice as efficient": "步兵的效率是两倍",
    "Gunners are three times as efficient": "枪手的效率是三倍",
    "All of your upcoming(s) combined generates": "您所有即将到来组合生成",
    "butcher(s).": "屠夫。",
    "gunner(s).": "枪手。",
    "Each upcoming generates": "每一个即将到来生成",
    "marksman(s).": "神枪手。",
    "infantry(s).": "步兵。",
    "more bazooka(s": "更多火箭筒",
    "more butcher(s": "更多屠夫",
    "more defender(s": "更多后卫",
    "more engineer(s": "更多工程师",
    "more grenadier(s": "更多手榴弹",
    "more gunner(s": "更多炮手",
    "more infantry(s": "更多步兵",
    "more marksman(s": "更多神射手",
    "more medic(s": "更多医生",
    "more pyro(s": "更多 火焰兵",
    "more rookie(s": "更多新秀",
    "more sapper(s": "更多工兵",
    "more sniper(s": "更多狙击手",
    "more upcoming(s": "更多即将到来",
    "rookie(s).": "菜鸟。",
    "upcoming(s).": "即将到来。",
    "Snipers are three times as efficient": "狙击手的效率是其三倍",
    "sniper(s).": "狙击手。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t\t": "\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Buy x": "购买 x",
    "Clicker ": "点击器 ",
    "Power Clicks ": "能量点击器 ",
    "Private ": "列兵 ",
    "Commando ": "突击队 ",
    "Cadet ": "学员 ",
    "Powerful Clones ": "更强大的克隆 ",
    "Pyro ": "火焰兵 ",
    "Rookie ": "菜鸟 ",
    "Sapper ": "工兵 ",
    "Bazooka ": "火箭筒 ",
    "Defender ": "防御者 ",
    "Butcher ": "屠夫 ",
    "Grenadier ": "掷弹兵 ",
    "Gunner ": "枪手 ",
    "Infantry ": "步兵 ",
    "Marksman ": "神射手 ",
    "Medic ": "医生 ",
    "Engineer ": "工程师 ",
    "Sniper ": "狙击手 ",
    "Striker ": "前锋 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\n\t": "\n\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) Q$/,
    /^([\d\.]+) O$/,
    /^([\d\.]+) S$/,
    /^([\d\.]+) SS$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) N$/,
    /^([\d\.]+) QQ$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);